// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {ERC4626} from "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title BrierVault
 * @notice An ERC4626 compliant vault for algorithmic prediction market pools.
 * @dev This contract holds USDC deposited by investors. The Brier Protocol daemon
 * is the only entity allowed to execute trades using this capital (mirroring the bot builder).
 * The Bot Builder CANNOT access or withdraw these funds.
 */
contract BrierVault is ERC4626, Ownable {
    
    // The address of the Brier Protocol Shadow Daemon (the indexer)
    address public brierDaemon;
    
    // The Polymarket Conditional Token Framework address
    address public polymarketCTF;
    
    // The registered execution wallet of the Bot Builder (for auditing/tracking)
    address public builderWallet;
    
    // Total profit generated by the vault (used to calculate builder performance fees)
    uint256 public totalProfit;

    // Events
    event TradeExecuted(bytes32 indexed conditionId, uint256 amount);
    event PerformanceFeePaid(address indexed builder, uint256 amount);

    /**
     * @param asset_ The underlying asset (e.g., USDC)
     * @param vaultName_ The name of the vault token (e.g., "Brier Vault: Alpha Strike")
     * @param vaultSymbol_ The symbol of the vault token (e.g., "bvALPHA")
     * @param _brierDaemon Address of the Brier background indexer
     * @param _builderWallet The bot builder's registered wallet
     * @param _polymarketCTF The Polymarket contract address
     */
    constructor(
        IERC20 asset_,
        string memory vaultName_,
        string memory vaultSymbol_,
        address _brierDaemon,
        address _builderWallet,
        address _polymarketCTF
    ) ERC4626(asset_) ERC20(vaultName_, vaultSymbol_) Ownable(msg.sender) {
        brierDaemon = _brierDaemon;
        builderWallet = _builderWallet;
        polymarketCTF = _polymarketCTF;
    }

    /**
     * @notice Modifier to ensure only the Brier Daemon can execute mirror trades.
     */
    modifier onlyDaemon() {
        require(msg.sender == brierDaemon, "BrierVault: Caller is not the daemon");
        _;
    }

    /**
     * @notice Executes a mirror trade on Polymarket.
     * @dev This is called automatically by the Brier Daemon when it detects the builder 
     * making a trade with their own capital.
     * @param conditionId The Polymarket market condition
     * @param partition The outcome partition array
     * @param amount The amount of USDC to deploy from the vault
     */
    function executeMirrorTrade(
        bytes32 conditionId,
        uint256[] calldata partition,
        uint256 amount
    ) external onlyDaemon {
        require(amount <= totalAssets(), "BrierVault: Insufficient vault liquidity");
        
        // 1. Approve CTF to spend USDC
        IERC20(asset()).approve(polymarketCTF, amount);
        
        // 2. Call splitPosition on Polymarket CTF to buy outcome tokens
        // (Mocked CTF interaction for clarity)
        (bool success, ) = polymarketCTF.call(
            abi.encodeWithSignature(
                "splitPosition(address,bytes32,bytes32,uint256[],uint256)",
                asset(),
                bytes32(0), // parent collection
                conditionId,
                partition,
                amount
            )
        );
        require(success, "BrierVault: CTF splitPosition failed");

        emit TradeExecuted(conditionId, amount);
    }

    /**
     * @notice Settles a resolved market and claims winnings.
     * @dev Upon winning, 10% of the profit is immediately routed to the Bot Builder.
     */
    function settleMarket(bytes32 conditionId, uint256 initialInvestment, uint256 payout) external onlyDaemon {
        // (Mocked CTF interaction to redeem positions)
        
        // If trade was profitable, calculate performance fee
        if (payout > initialInvestment) {
            uint256 profit = payout - initialInvestment;
            uint256 builderFee = (profit * 10) / 100; // 10% Performance Fee
            
            totalProfit += profit;
            
            // Transfer fee to builder
            IERC20(asset()).transfer(builderWallet, builderFee);
            emit PerformanceFeePaid(builderWallet, builderFee);
        }
    }

    /**
     * @notice Emergency function to update the Daemon address if keys are rotated.
     * Only the Brier Protocol Admin can call this.
     */
    function setDaemon(address _newDaemon) external onlyOwner {
        brierDaemon = _newDaemon;
    }
}
